// GENERATED by scripts/sync-upstream-baseline.mjs — do not edit by hand.
//
// Offline snapshot of the atomic-chat-conf backend manifest. `fetchRemoteBackends`
// parses it as a last resort when every network transport fails (ATO-243), so it
// deliberately carries real tags and backend ids: the download path keeps
// working, it is just older than the live manifest until the network recovers.
//
// Regenerate with `make sync-upstream-baseline` after the manifest moves. The
// tag here is NOT a pin — a live manifest on a newer tag is followed as-is.
import type { UpstreamManifest } from './backend'

export const BUNDLED_MANIFEST_BASELINE: UpstreamManifest = {
  tag_name: 'b10344',
  assets: [
    { name: 'llama-b10344-bin-win-cpu-x64.zip' },
    { name: 'llama-b10344-bin-win-cuda-12.4-x64.zip' },
    { name: 'llama-b10344-bin-win-cuda-13.3-x64.zip' },
    { name: 'llama-b10344-bin-win-vulkan-x64.zip' },
    { name: 'llama-b10344-bin-ubuntu-x64.tar.gz' },
    { name: 'llama-b10344-bin-ubuntu-vulkan-x64.tar.gz' },
    { name: 'llama-b10344-bin-macos-arm64.tar.gz' },
    { name: 'cudart-llama-bin-win-cuda-12.4-x64.zip' },
    { name: 'cudart-llama-bin-win-cuda-13.3-x64.zip' },
  ],
}
